//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.SSC.BL {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TS.SSC.BL.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a delete from  Tbl_Parroquia
        ///where id=@id;.
        /// </summary>
        internal static string ParroquiaDelete {
            get {
                return ResourceManager.GetString("ParroquiaDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a insert into  Tbl_Parroquia
        ///(
        ///nombre,
        ///lugar,
        ///direccion,
        ///telefono,
        ///parroco,
        ///fechaCrea,
        ///userCrea
        ///)
        ///Values
        ///(
        ///@nombre,
        ///@lugar,
        ///@direccion,
        ///@telefono,
        ///@parroco,
        ///getdate(),
        ///@userCrea
        ///).
        /// </summary>
        internal static string ParroquiaInsert {
            get {
                return ResourceManager.GetString("ParroquiaInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select * from Tbl_Parroquia
        ///where id = @id;.
        /// </summary>
        internal static string ParroquiaSelect {
            get {
                return ResourceManager.GetString("ParroquiaSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a update Tbl_Parroquia
        ///set
        ///nombre=@nombre,
        ///lugar=@lugar,
        ///direccion=@direccion,
        ///telefono=@telefono,
        ///parroco=@parroco,
        ///fechaModif=getdate(),
        ///userModif=@userModif;
        ///.
        /// </summary>
        internal static string ParroquiaUpdate {
            get {
                return ResourceManager.GetString("ParroquiaUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a insert into Tbl_Persona
        ///(idParroquia, cedula, nombre,nombrePadre, nombreMadre,
        ///fechaNacimiento, lugarNacimiento, fechaBautismo, lugarBautismo,
        ///fechaCrea,userCrea)
        ///values
        ///(@idParroquia, @cedula,@nombre,@nombrePadre,@nombreMadre,
        ///@fechaNacimiento,@lugarNacimiento,@fechaBautismo,
        ///@lugarBautismo,Getdate(),@userCrea);
        ///SELECT SCOPE_IDENTITY();.
        /// </summary>
        internal static string PersonaInsert {
            get {
                return ResourceManager.GetString("PersonaInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete from Tbl_Persona
        ///where id= @id;.
        /// </summary>
        internal static string PersonalDelete {
            get {
                return ResourceManager.GetString("PersonalDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select * from Tbl_Persona
        ///where idParroquia = @idParroquia
        ///and id=@id;
        ///.
        /// </summary>
        internal static string PersonaSelect {
            get {
                return ResourceManager.GetString("PersonaSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Tbl_Persona
        ///set
        ///idParroquia= @idParroquia, 
        ///cedula=@cedula, 
        ///nombre=@nombre,nombrePadre=@nombrePadre, nombreMadre=@nombreMadre,
        ///fechaNacimiento=@fechaNacimiento, lugarNacimiento=@lugarNacimiento, fechaBautismo=@fechaBautismo, 
        ///lugarBautismo=@lugarBautismo,userModif=@userModif,fechaModif=getdate()
        ///where id = @id;.
        /// </summary>
        internal static string PersonaUpdate {
            get {
                return ResourceManager.GetString("PersonaUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select a.*,
        ///b.nombre as Parroquia,
        ///c. nombreSacramento as Sacramento,
        ///d.nombre as Persona
        ///from Tbl_RegistroSacramento a
        ///inner join Tbl_Parroquia b on a.idParroquia = b.id
        ///inner join Tbl_Sacramentos c on a.idSacramento = c.id
        ///inner join Tbl_Persona d on  a.idPersona = d.id
        ///where a.idParroquia = @idParroquia
        ///and a.id = @id;.
        /// </summary>
        internal static string RegistroSacramentoConsulta {
            get {
                return ResourceManager.GetString("RegistroSacramentoConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete from Tbl_RegistroSacramento
        ///where id=@id;.
        /// </summary>
        internal static string RegistroSacramentoDelete {
            get {
                return ResourceManager.GetString("RegistroSacramentoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a insert into Tbl_RegistroSacramento
        ///(
        ///idParroquia,
        ///idPersona,
        ///idSacramento,
        ///fechaRegistro,
        ///libro,
        ///folio,
        ///partida,
        ///nombrePadrino,
        ///nombreMadrina,
        ///nombreMinistro,
        ///nombreDaFe,
        ///fechaCrea,
        ///userCrea
        ///)
        ///Values
        ///(
        ///@idParroquia,
        ///@idPersona,
        ///@idSacramento,
        ///@fechaRegistro,
        ///@libro,
        ///@folio,
        ///@partida,
        ///@nombrePadrino,
        ///@nombreMadrina,
        ///@nombreMinistro,
        ///@nombreDaFe,
        ///getdate(),
        ///@userCrea
        ///);
        ///SELECT SCOPE_IDENTITY();
        ///.
        /// </summary>
        internal static string RegistroSacramentoInsert {
            get {
                return ResourceManager.GetString("RegistroSacramentoInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select * from Tbl_RegistroSacramento
        ///where idParroquia = @idParroquia
        ///and id = @id;.
        /// </summary>
        internal static string RegistroSacramentoSelect {
            get {
                return ResourceManager.GetString("RegistroSacramentoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update Tbl_RegistroSacramento
        ///set
        ///idParroquia=@idParroquia,
        ///idPersona=@idPersona,
        ///idSacramento=@idSacramento,
        ///fechaRegistro=@fechaRegistro,
        ///libro=@libro,
        ///folio=@folio,
        ///partida=@partida,
        ///nombrePadrino=@nombrePadrino,
        ///nombreMadrina=@nombreMadrina,
        ///nombreMinistro=@nombreMinistro,
        ///nombreDaFe=@nombreDaFe,
        ///fechaModif = getdate(),
        ///userModif = @userModif
        ///where id=@id.
        /// </summary>
        internal static string RegistroSacramentoUpdate {
            get {
                return ResourceManager.GetString("RegistroSacramentoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a delete from Tbl_Sacramentos
        ///where id = @id;.
        /// </summary>
        internal static string SacramentoDelete {
            get {
                return ResourceManager.GetString("SacramentoDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert into Tbl_Sacramentos
        ///(nombreSacramento,
        ///estado,
        ///fechaCrea,
        ///userCrea)
        ///Values
        ///(@nombreSacramento,
        ///@estado,
        ///getdate(),
        ///@userCrea);.
        /// </summary>
        internal static string SacramentoInsert {
            get {
                return ResourceManager.GetString("SacramentoInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select * from  Tbl_Sacramentos 
        ///where id = @id;.
        /// </summary>
        internal static string SacramentoSelect {
            get {
                return ResourceManager.GetString("SacramentoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a update Tbl_Sacramentos
        ///set
        ///nombreSacramento=@nombreSacramento,
        ///estado=@estado,
        ///fechaModif=getdate(),
        ///userModif=@userModif
        ///where id=@id;.
        /// </summary>
        internal static string SacramentoUpdate {
            get {
                return ResourceManager.GetString("SacramentoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Tbl_Usuario
        ///where id = @id;.
        /// </summary>
        internal static string UsuarioDelete {
            get {
                return ResourceManager.GetString("UsuarioDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a insert into Tbl_Usuario
        ///(idParroquia, userName, &quot;password&quot;,passwordHash, 
        ///tipoUsuario, nombreUsuario, estado,
        ///fechaCrea, userCrea)
        ///values
        ///(
        ///@idParroquia, @userName, @password,@passwordHash, 
        ///@tipoUsuario, @nombreUsuario, @estado,
        ///getdate(), @userCrea
        ///).
        /// </summary>
        internal static string UsuarioInsert {
            get {
                return ResourceManager.GetString("UsuarioInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a select * from Tbl_Usuario where
        ///idParroquia = @idParroquia
        ///and id = @id
        ///and userName = @userName
        ///and password = @password
        ///.
        /// </summary>
        internal static string UsuarioSelect {
            get {
                return ResourceManager.GetString("UsuarioSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a update Tbl_Usuario
        ///Set
        ///idParroquia=@idParroquia, 
        ///userName=@userName, 
        ///&quot;password&quot;=@password,
        ///passwordHash=@passwordHash, 
        ///tipoUsuario=@tipoUsuario, 
        ///nombreUsuario=@nombreUsuario, 
        ///estado=@estado,
        ///fechaModif= getdate(), 
        ///userModif=@userModif
        ///where id= @id;.
        /// </summary>
        internal static string UsuarioUpdate {
            get {
                return ResourceManager.GetString("UsuarioUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a update Tbl_Usuario
        ///Set
        ///&quot;password&quot;=@password,
        ///passwordHash=@passwordHash, 
        ///fechaModif= getdate(), 
        ///userModif=@userModif
        ///where id= @id;.
        /// </summary>
        internal static string UsuarioUpdatePass {
            get {
                return ResourceManager.GetString("UsuarioUpdatePass", resourceCulture);
            }
        }
    }
}
